// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChte_wF1-kKAANx2hKjwW3pxRtzGpa8rQ',
    appId: '1:60904297622:web:dfe836e6ff7dcedc0e9eb7',
    messagingSenderId: '60904297622',
    projectId: 'flutter-71af7',
    authDomain: 'flutter-71af7.firebaseapp.com',
    storageBucket: 'flutter-71af7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjI_Cvk7ohGOaQOPRITR90GCKMtzx4ynk',
    appId: '1:60904297622:android:6892375669336e880e9eb7',
    messagingSenderId: '60904297622',
    projectId: 'flutter-71af7',
    storageBucket: 'flutter-71af7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRmQu0BJf18Sx_hzyV39VP3PpRdQ7zn70',
    appId: '1:60904297622:ios:fe81e357bb99d8150e9eb7',
    messagingSenderId: '60904297622',
    projectId: 'flutter-71af7',
    storageBucket: 'flutter-71af7.firebasestorage.app',
    iosBundleId: 'com.example.chatappFirebase',
  );
}
